### ISSUE TITLE
Unable to parse longPoll request: Error("missing field `is_unavailable`")

### ISSUE THREAD

**Issue by Huterenok** [Azumi4han/safe-vk#1]
Hi, trying to reproduce example with basic usage from README, but when i write something to bot it crashes on a server with error:
`thread 'tokio-runtime-worker' panicked at /home/huterok/Projects/Rust/regulyarOchka/safe-vk/src/methods.rs:193:40:
Unable to parse longPoll request: Error("missing field "is_unavailable":, line: 0, column: 0)
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`
I tried to clone repository and delete `is_unavailable` field from `Message` struct and it worked. Not making pull request as I am not so familiar with the VK api and may be wrong somewhere.

**Comment by Azumi4han** [comment]
Hi, thank you for your pull request and for highlighting this bug. I'm planning to fix this issue in an upcoming update, and I'll review the VK API again to ensure that similar issues do not occur.

**Comment by Vas-Sferd** [comment]
Bug still here. I send pull request today (upd 25.03.2024)

**Comment by Azumi4han** [comment]
The issue has been resolved and I'm closing this issue. For more details, see the closed pull request here: [pull request](https://github.com/Azumi4han/safe-vk/pull/2). Thanks for your patience.
